Add email on terminated option
Australian-Structural-Biology-Computing/kod-proteinfold pull request #14
Opened 2024-11-22 04:22 UTC by keiran-rowell-unsw

2024-11-22 04:51 UTC, keiran-rowell-unsw reviewed
whoops, should have @ad.unsw.edu to be safe, 'USER' will always resolve to zID on Katana

2024-11-26 00:36 UTC, nbtm-sh commented
@keiran-rowell-unsw you need to make the change as it will prevent me from approving this request if I push to this branch

2024-11-26 00:37 UTC, nbtm-sh requested changes

2024-11-26 00:37 UTC, nbtm-sh commented on submit.yml.erb
> +        - "<%= ENV['USER'] %>@unsw.edu.au"
Needs to be `$USER@ad.unsw.edu.au`

2024-12-13 00:17 UTC, nbtm-sh approved these changes
Looks good to me

2024-12-13 00:17 UTC, merged